name: docs

on:
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/docs.yml', 'docs/index.html' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/docs.yml', 'docs/index.html' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Checkout the gh-pages branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        ref: gh-pages
        path: docs

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build docs with Maven
      run: mvn compile javadoc:javadoc

    - name: Copy to Documentation Website Location
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        rm -rf docs/api
        cp -rf target/site/apidocs/. docs/api	

    - name: Tidy up the javadocs
      if: ${{ github.event_name != 'pull_request' }}
      id: tidy
      uses: cicirello/javadoc-cleanup@v1
      with:
        base-url-path: https://core.cicirello.org/
        path-to-root: docs

    - name: Log javadoc-cleanup output
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

    - name: Commit documentation changes without pushing
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd docs
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Vincent A. Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add -A
          git commit -m "Automated API website updates."
        fi
        cd ..

    - name: Generate the sitemap
      if: ${{ github.event_name != 'pull_request' }}
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://core.cicirello.org/
        path-to-root: docs

    - name: Output stats
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Commit documentation website sitemap and push all commits
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd docs
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Vincent A. Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add -A
          git commit -m "Automated API website updates."
        fi
        git push
        cd ..

