# Triggers a snapshot build on JitPack for the custom domain.
# Already have a webhook setup, but that won't trigger the build
# for the custom domain.

name: jitpack-build

on:
  push:
    branches: [ main ]

jobs:
  jitpack:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Request main-SNAPSHOT from JitPack
      run: |
        # timeout in 10 seconds to avoid waiting for build
        STATUS=$(curl -s -m 10 https://jitpack.io/org/cicirello/core/main-SNAPSHOT/)
        exit 0
